---

################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/supply.com/msp

    - &Org1
        Name: Org1MSP
        ID: Org1MSP
        MSPDir: crypto-config/peerOrganizations/org1.supply.com/msp

        AnchorPeers:
            - Host: peer0.org1.supply.com
              Port: 7051

    - &Org2
        Name: Org2MSP
        ID: Org2MSP
        MSPDir: crypto-config/peerOrganizations/org2.supply.com/msp

        AnchorPeers:
            - Host: peer0.org2.supply.com
              Port: 7051
    - &Org3
        Name: Org3MSP
        ID: Org3MSP
        MSPDir: crypto-config/peerOrganizations/org3.supply.com/msp

        AnchorPeers:
            - Host: peer0.org3.supply.com
              Port: 7051

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    OrdererType: kafka
    Addresses:
        - orderer.supply.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 20 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - kafka0.dash.com:9092
            - kafka1.dash.com:9092
            - kafka2.dash.com:9092
            - kafka3.dash.com:9092
    Organizations:

Application: &ApplicationDefaults

    Organizations:


################################################################################
#
#   Profile
#
#   - define supplyOrgsOrdererGenesis and supplyOrgsChannel
#
################################################################################
Profiles:

    supplyOrgsOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1
                    - *Org2
                    - *Org3

    supplyOrgsChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
                - *Org3
